version: '3.8'

services:

  config-server:
    image: config-server:latest
    build:
      context: ./ConfigServer
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8484:8484"
    networks:
      - microservices-network
    restart: unless-stopped

  eureka-server:
    image: eureka-server:latest
    build:
      context: ./ServiceDiscovery
      dockerfile: Dockerfile
    container_name: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8484
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    restart: unless-stopped

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./GatewayApi
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8484
      - EUREKA_URL=http://eureka-server:8761/eureka/
    ports:
      - "8089:8089"
    depends_on:
      - config-server
      - book-microservice-command
      - book-microservice-query
      - library-microservice-command
      - library-microservice-query
      - eureka-server
      - keycloak
    networks:
      - microservices-network
    restart: unless-stopped

  book-microservice-command:
    image: book-microservice-command:latest
    build:
      context: ./BookMicroserviceCommand
      dockerfile: Dockerfile
    container_name: book-microservice-command
    ports:
      - "8181:8181"
    depends_on:
      - config-server
      - eureka-server
      - mysql
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8484
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=bookMicroserviceCommand
      - DB_USERNAME=bookuser
      - DB_PASSWORD=bookpassword
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - microservices-network
    restart: unless-stopped

  book-microservice-query:
    image: book-microservice-query:latest
    build:
      context: ./BookMicroserviceQuery
      dockerfile: Dockerfile
    container_name: book-microservice-query
    depends_on:
      - config-server
      - eureka-server
      - mysql
      - kafka
    ports:
      - "8182:8182"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8484
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=bookMicroserviceQuery
      - DB_USERNAME=bookuser
      - DB_PASSWORD=bookpassword
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - microservices-network
    restart: unless-stopped

  library-microservice-command:
    image: library-microservice-command:latest
    build:
      context: ./LibrarayMicroserviceCommand
      dockerfile: Dockerfile
    container_name: library-microservice-command
    ports:
      - "8282:8282"
    depends_on:
      - config-server
      - eureka-server
      - mongodb
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8484
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - DB_NAME=libraryMicroserviceCommand
      - DB_HOST=mongodb
      - MONGO_URL=mongodb://mongodb:27017/libraryMicroserviceCommand
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: unless-stopped
    networks:
      - microservices-network

  library-microservice-query:
    image: library-microservice-query:latest
    build:
      context: ./LibrarayMicroserviceQuery
      dockerfile: Dockerfile
    container_name: library-microservice-query
    ports:
      - "8283:8283"
    depends_on:
      - config-server
      - eureka-server
      - mongodb
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8484
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - DB_NAME=libraryMicroserviceCommand
      - DB_HOST=mongodb
      - MONGO_URL=mongodb://mongodb:27017/libraryMicroserviceCommand
      - BOOK_QUERY_MICROSERVICE_URL=http://book-microservice-query:8182
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - microservices-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookdb
      MYSQL_USER: bookuser
      MYSQL_PASSWORD: bookpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservices-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - microservices-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - microservices-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - microservices-network
  
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    command: ["start-dev"]
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakpassword
    ports:
      - "8088:8080"
    depends_on:
      - postgres
    networks:
      - microservices-network
    restart: unless-stopped

  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    name: microservices-network
    driver: bridge

volumes:
  mysql-data:
  mongodb-data:
  postgres-data:
